version: '3.1'
services:
  renovate:
    image: renovate/renovate
    ports:
      - "7500:7600"
    volumes:
      - ./config.js:/usr/src/app/config.js      
      - ./custom_secrets.js:/usr/src/app/custom_secrets.js      